# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "doXno7wfI6XDWwQQDdco3uR6hMAjucm5lLEw/W0rJvryAY7RiMOab7EwBj0WbcrXPoWcWNEisd3sUESDrwrY4bJJF6tv6A+p6oblwKQSKIXcVmO7V/0u9tcamg8D99J4pWgjcJBnuNsx+lku8pwAzdZJDFRtMD0V3x5jAY2/PUbVuFZJBR/L+XB/swAUPNGH/q++O4z0R6yp0KBhXuLboOI/I+yjHJa2gvEe5qP2d2+PrLHzSa+N7UJrX9+BtZlrMYc5moTrPj+RMg25fTXxNPK8I3u54TgtfuZ3Oi0TupBea5/6QuVqv0Jq7fOgPclmiy016NNhCCFOXfxBdawMuoCS1+hOFuOCUWQoKsaBJpH75rquSv1B1Mb4yAaSs2+CWwn39Rc5MKsU8D6HsuWauyrvtLzOsvcKR7ZhALRcPDAm7kd15QGNes3ZknGD+yRa3/5HfF9f/8XicgOClFkE0g5wC+glR44bSgyiHu5qpQngHHlo/zc/VwnwZHIDSgJ031m/fV4GpP9/08TeRlJYY0MP9nqqdjzyv6fRymHxa+cnHuIooPGuw6j/yvWYhl5xbRhy5z5hJEnY3HP1lbKd4GZuY9vibMWWqdBDCdpNMPx1KZSyOLVtgbHVdp2KYXv2dCuMV6J4bZjAg9GUNpYuOPUmAFENRerhOANtIiZGmRw="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
