travis:
  secure:
    BINSTAR_TOKEN: doXno7wfI6XDWwQQDdco3uR6hMAjucm5lLEw/W0rJvryAY7RiMOab7EwBj0WbcrXPoWcWNEisd3sUESDrwrY4bJJF6tv6A+p6oblwKQSKIXcVmO7V/0u9tcamg8D99J4pWgjcJBnuNsx+lku8pwAzdZJDFRtMD0V3x5jAY2/PUbVuFZJBR/L+XB/swAUPNGH/q++O4z0R6yp0KBhXuLboOI/I+yjHJa2gvEe5qP2d2+PrLHzSa+N7UJrX9+BtZlrMYc5moTrPj+RMg25fTXxNPK8I3u54TgtfuZ3Oi0TupBea5/6QuVqv0Jq7fOgPclmiy016NNhCCFOXfxBdawMuoCS1+hOFuOCUWQoKsaBJpH75rquSv1B1Mb4yAaSs2+CWwn39Rc5MKsU8D6HsuWauyrvtLzOsvcKR7ZhALRcPDAm7kd15QGNes3ZknGD+yRa3/5HfF9f/8XicgOClFkE0g5wC+glR44bSgyiHu5qpQngHHlo/zc/VwnwZHIDSgJ031m/fV4GpP9/08TeRlJYY0MP9nqqdjzyv6fRymHxa+cnHuIooPGuw6j/yvWYhl5xbRhy5z5hJEnY3HP1lbKd4GZuY9vibMWWqdBDCdpNMPx1KZSyOLVtgbHVdp2KYXv2dCuMV6J4bZjAg9GUNpYuOPUmAFENRerhOANtIiZGmRw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
